export const GET_DATA = "GET_DATA";

export const FETCH_CLEANING_DATA = "FETCH_CLEANING_DATA";

export const FETCH_COVID_DATA = "FETCH_COVID_DATA";

export const FIRESTORE_COVID = "FIRESTORE_COVID";

export const FETCH_FIRESTORE_TOPIC_UNIT = "FETCH_FIRESTORE_TOPIC_UNIT";
