export const FIRESTORE_COVID = "FIRESTORE_COVID";

export const FETCH_FIRESTORE_TOPIC_UNIT = "FETCH_FIRESTORE_TOPIC_UNIT";

export const USER_DATA = "USER_DATA";

export const LOGOUT = "LOGOUT";

export const FETCH_TOPIC_LIST = "FETCH_TOPIC_LIST";
